server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-courseM
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
